name: Deploy React App to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build React App
      run: |
        npm install
        npm run build dev

    - name: Deploy to IIS via Ngrok
      run: |
        curl -X POST ${{ secrets.NGROK_URL }}/deploy -H "Content-Type: application/json" -d '{
          "command": "cd C:\inetpub\DeployActions && git pull origin main"
        }'
