name: Deploy to Local Server via Ngrok

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Local IIS via Ngrok
      run: |
        curl -X POST ${{ secrets.NGROK_URL }}/deploy -H "Content-Type: application/json" -d '{
          "command": "git pull origin main && iisreset"
        }'
