name: Deploy React App to IIS

on:
  push:
    branches:
      - main  # Ejecuta el workflow al hacer push en la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install
          npm run build  # Genera la carpeta 'build'

      - name: Deploy to IIS via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh -o StrictHostKeyChecking=no hp-envy@192.168.3.180 "rm -rf /inetpub/DeployActions/*"
          scp -r ./build/* hp-envy@192.168.3.180:/inetpub/DeployActions/

      - name: Restart IIS (optional)
        run: |
          ssh <usuario>@<ip-servidor> "iisreset"
