name: Deploy React to IIS by runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Utiliza el runner auto-hospedado

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: powershell -ExecutionPolicy Bypass -Command "npm install"

    - name: Build React app
      run: npm run build

    - name: List files for debugging
      run: ls -la && ls -la dist || echo "Dist directory not found"

    - name: Copy files to IIS server
      run: |
        # Si el runner ya está en el servidor IIS, puedes usar comandos locales en lugar de SCP
        # Suponiendo que tienes IIS configurado para recibir los archivos
        xcopy /E /I /Y dist\* C:\inetpub\DeployActions\

    - name: Notify Teams
      run: |
        curl -H 'Content-Type: application/json' \
          -d '{"text":"El despliegue de ${{ vars.NOMBRE_PROYECTO }} ha sido completado exitosamente en el servidor IIS desde GitHub"}' \
          https://iberomx.webhook.office.com/webhookb2/b69cf58a-145e-4bc3-a475-640753321d68@40152134-6f8a-46f7-bc22-240f7c7c2455/IncomingWebhook/8ab337806a4f48a6bac8364964376f87/cfafb0dc-c85f-48b5-b351-7987e37a8b4c/V25b0WXu1B_fsmLHVdlXEEtWZp1mybiHnxBRsA8DOw8S81
