name: Deploy React to IIS by runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Utiliza el runner auto-hospedado

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    # Configuración de Node.js con una versión más reciente, por ejemplo 18
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Mejor usar una versión más reciente de Node.js

    # Limpiar el cache de node_modules y reinstalar dependencias
    - name: Install dependencies
      run: |
        npm ci  # npm ci es más rápido y fiable para CI/CD ya que limpia node_modules
    # Crear build del proyecto React
    - name: Build React app
      run: npm run build

    # Listar archivos generados para debug (verificar dist)
    - name: List files for debugging
      run: |
        ls -la
        if (-Not (Test-Path dist)) {
          Write-Host "Dist directory not found"
        } else {
          ls -la dist
        }
    # Asegurarte de que el directorio de destino existe antes de copiar
    - name: Ensure deployment directory exists
      run: |
        if (-not (Test-Path "C:\inetpub\DeployActions\")) {
          New-Item -Path "C:\inetpub\DeployActions\" -ItemType Directory
        }
    # Copiar los archivos generados al servidor IIS
    - name: Copy files to IIS server
      run: |
        xcopy /E /I /Y dist\* C:\inetpub\DeployActions\
    # Notificar por Teams al finalizar el despliegue
    - name: Notify Teams
      run: |
        curl -H 'Content-Type: application/json' \
          -d '{"text":"El despliegue de '${{ vars.NOMBRE_PROYECTO }}' ha sido completado exitosamente en el servidor IIS desde GitHub"}' \
          ${{ secrets.TEAMS_WEBHOOK_URL }}
